// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApTrQyeFDCmLtiCFM5ToqwC4GLeUJ9o-A',
    appId: '1:768981118108:web:1f9225795d669fb1a75159',
    messagingSenderId: '768981118108',
    projectId: 'together-c110b',
    authDomain: 'together-c110b.firebaseapp.com',
    storageBucket: 'together-c110b.appspot.com',
    measurementId: 'G-BJVW428QXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhX6jmEaP0hJpGJTrXzYBJmSZrRrhT49w',
    appId: '1:768981118108:android:57dfe1c5f25b8350a75159',
    messagingSenderId: '768981118108',
    projectId: 'together-c110b',
    storageBucket: 'together-c110b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5oOiaHmeOoyWzBdmB3rur2lOCfdDmoJc',
    appId: '1:768981118108:ios:e1787a14cc429195a75159',
    messagingSenderId: '768981118108',
    projectId: 'together-c110b',
    storageBucket: 'together-c110b.appspot.com',
    iosBundleId: 'com.example.together',
  );
}
